/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/6.8.3/samples
 */

version = "0.1.0"
val junitVersion = "5.3.1"
val hamcrestVersion = "2.2"
val docsDir = "build/docs"

plugins {
    // plugins block cannot read the outerscope
    kotlin("jvm") version "1.4.31"
    id("org.jetbrains.dokka") version "1.4.20"
}

repositories {
    jcenter()
}


sourceSets {
    main {
        java {
            setSrcDirs(listOf("src/main/kotlin/algo", "src/main/kotlin/ds"))
        }
    }

    test {
        java {
            setSrcDirs(listOf("src/main/test/kotlin/algo", "src/main/test/kotlin/ds"))
        }
    }
}

dependencies{
    testImplementation("org.jetbrains.kotlin:kotlin-test")
    implementation("com.google.guava:guava:29.0-jre")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")
    testImplementation("org.hamcrest:hamcrest:${hamcrestVersion}")
    testImplementation("org.junit.jupiter:junit-jupiter-api:${junitVersion}")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:${junitVersion}")
}

tasks.test {
    useJUnitPlatform()
    maxHeapSize = "1G"
    maxParallelForks = 5
}

tasks.jar {
    manifest {
        attributes(mapOf("Implementation-Title" to project.name,
                "Implementation-Version" to project.version))
    }
}


tasks.dokkaHtml.configure {
    outputDirectory.set(buildDir.resolve(docsDir))
}